services:
  accounts:
    image: "hikmatullo2904/accounts:v1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 1024m
  cards:
    image: "hikmatullo2904/cards:v1"
    container_name: cards-ms
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          memory: 1024m
  loans:
    image: "hikmatullo2904/loans:v1"
    container_name: loans-ms
    ports:
      - "8082:8082"
    deploy:
      resources:
        limits:
          memory: 1024m
