services:
  configserver:
    image: "hikmatullo2904/configserver:v1"
    container_name: configserver
    ports:
      - "8071:8071"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - hikmatullo
  accounts:
    image: "hikmatullo2904/accounts:v1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - hikmatullo
  loans:
    image: "hikmatullo2904/loans:v1"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - hikmatullo
  cards:
    image: "hikmatullo2904/cards:v1"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - hikmatullo
networks:
  eazybank:
    driver: "bridge"